export const options = [
    "React",
    "Next.js",
    "Node.js",
    "Express",
    "MongoDB",
    "PostgreSQL",
    "Redis",
    "Docker",
    "Nginx",
    "Kubernetes",
    "AWS",
    "GraphQL",
    "TypeScript",
    "Tailwind CSS",
    "SASS",
    "Jenkins",
    "Git",
    "GitHub",
    "CI/CD",
    "Firebase",
    "Heroku",
    "Google Cloud",
    "Azure",
    "Webpack",
    "Vite",
    "Flutter",
    "React Native",
    "Terraform",
    "Ansible",
    "Linux",
    "Jest",
    "Cypress",
    "ElasticSearch",
    "RabbitMQ",
    "Kafka",
    "Redux",
    "Vercel",
    "DigitalOcean",
    "PHP",
    "Laravel",
    "MySQL",
    "GraphQL",
    "Apollo",
    "Angular",
    "Vue.js",
    "RxJS",
    "Electron",
    "Figma",
    "Adobe XD"
];
